# Generated by Django 2.0.2 on 2019-04-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='验证码'),
        ),
    ]
