# Generated by Django 2.0.2 on 2019-05-06 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrueAndFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='正确率')),
                ('wrong_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='错误率')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户正确与错误率',
                'verbose_name_plural': '用户正确与错误率',
            },
        ),
    ]
