# Generated by Django 2.0.2 on 2019-04-22 18:42

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, verbose_name='答案')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类别名', max_length=100, verbose_name='类别名')),
                ('category_type', models.IntegerField(choices=[(1, '一级类别'), (2, '二级类别')], default=1, help_text='类别级别', verbose_name='类别级别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='当前类别的父级', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='topic.Category', verbose_name='当前类别的父级')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='题目')),
                ('option_a', models.CharField(max_length=100, verbose_name='a选项')),
                ('option_b', models.CharField(max_length=100, verbose_name='b选项')),
                ('option_c', models.CharField(max_length=100, verbose_name='c选项')),
                ('option_d', models.CharField(max_length=100, verbose_name='d选项')),
                ('desc', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subject/images/', verbose_name='图片')),
                ('fav_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='topic.Category', verbose_name='题目类别')),
            ],
            options={
                'verbose_name': '题目信息',
                'verbose_name_plural': '题目信息',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='topic.Subject', verbose_name='题目答案'),
        ),
    ]
