# Generated by Django 2.0.2 on 2019-04-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/images/', verbose_name='图片'),
        ),
    ]
