# Generated by Django 2.0.2 on 2019-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=300, verbose_name='题目'),
        ),
    ]
