# Generated by Django 2.0.2 on 2019-04-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20190422_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=2000, verbose_name='题目'),
        ),
    ]
