# Generated by Django 2.0.2 on 2019-04-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0007_examtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examtime',
            options={'verbose_name': '考试时间', 'verbose_name_plural': '考试时间'},
        ),
    ]
