# Generated by Django 2.0.2 on 2019-04-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0008_auto_20190423_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtime',
            name='exam_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='考试编号'),
        ),
    ]
