# Generated by Django 2.0.2 on 2019-05-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0010_answer_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='analysis',
            field=models.CharField(default='', max_length=2000, verbose_name='解析'),
        ),
    ]
