# Generated by Django 2.0.2 on 2019-05-06 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0011_auto_20190506_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightwrongsub',
            name='right_num',
        ),
        migrations.RemoveField(
            model_name='rightwrongsub',
            name='wrong_num',
        ),
        migrations.AlterField(
            model_name='rightwrongsub',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_wrong', to='topic.Subject', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='rightwrongsub',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
